### ISSUE TITLE
Bug when parsing coordinates of RIA meteorological stations

### ISSUE THREAD

**Issue by rubenfcasal** [emf-creaf/meteospain#20]
When comparing the representation of the coordinates of the RIA stations obtained with meteospain with the map on the official website (https://www.juntadeandalucia.es/agriculturaypesca/ifapa/riaweb/web/), I realized that there must be an error in the processing.

The package assumes that the geographical coordinates of RIA stations are retrieved in a decimal degree (DD) format, but in reality they are in "degrees", "minutes" and "seconds" (DMS) format.

The following function could be used to convert (longitude or latidude) in this DMS format (DDMMSSsssH) to numeric DD:
```r
.parse_coord_gmsh <- function(coord){
  gmsh <- stringr::str_sub_all(coord, 
        cbind(start = c(1, 3, 5, 10), length = c(2, 2, 5, 1)))
  sapply(gmsh, function(x) (as.numeric(x[1]) + as.numeric(x[2])/60 + 
         as.numeric(x[3])/3600000) * if (grepl(x[4],"W|S")) -1 else 1)
}
```

**Comment by MalditoBarbudo** [comment]
@rubenfcasal 

This is now fixed in main and devel branches, I will maintain the issue open until the new package version is in CRAN

**Comment by MalditoBarbudo** [comment]
New version [0.1.4](https://github.com/emf-creaf/meteospain/releases/tag/v0.1.4) on its way to CRAN, I'll close this.
