### ISSUE TITLE
Error when getting data (Error in UseMethod)

### ISSUE THREAD

**Issue by Polvi8** [emf-creaf/meteospain#22]
I've been working with the package with no issues until all of a sudden I started to get this error in any attempt to get data.

```
api_options <- meteocat_options(resolution = 'daily',
                                start_date = Sys.Date(),
                                api_key = key)

get_stations_info_from('meteocat', options = api_options)
```
Running the previous code results in this error ```Error in UseMethod("rename") : no applicable method for 'rename' applied to an object of class "NULL"```. Same happens if I use ```get_meteo_from()``` instead.

I've tried making sure everything is up to date and also checked for limits in the Meteocat API which could potentially cause this, but apparently it has nothing to do with that. I've also found that [I'm not the first one to get this error using the package](https://github.com/rstudio/pointblank/issues/122#issuecomment-985304206).

**Comment by MalditoBarbudo** [comment]
@Polvi8 
This usually happens when you exhaust your monthly quota in the meteocat API.
Check with `get_quota_from("meteocat", meteocat_options(api_key = key))` and look at the `XEMA` row. If is that, you have to wait until next month, or talk with MeteoCat for them to increase your monthly limit.
If is not that, please tell me for me too look deep on this.

**Comment by Polvi8** [comment]
Seems I was wrong with the limits!

As you said, after checking it the ```XEMA``` row, it indicates I have run out of monthy queries.

Thanks for the help!

**Comment by MalditoBarbudo** [comment]
No problem, and sorry for this. I've tried to capture better this precise error to give the correct message instead of this one about rename that is pretty generic. But the API is not consistent in the error codes or responses and it seems I can't find the way to capture it correctly.
