### ISSUE TITLE
MeteoClimatic API failing

### ISSUE THREAD

**Issue by MalditoBarbudo** [emf-creaf/meteospain#24]
MeteoClimatic API has changed domain from .com to .net
CRAN version doesn't work, github devel version works.

**Comment by xavidp** [comment]
I confirm this currently works on the devel version.
(And ported the equivalent change to a local copy of the meteoclimaticR package - the one that allows fetching historic data from meteoclimatic) and I was able to fetch that historic data again.  Thanks for the pointer and fix in meteospain devel!
