### ISSUE TITLE
HR missing in AEMET daily records

### ISSUE THREAD

**Issue by xavidp** [emf-creaf/meteospain#26]
Hi @MalditoBarbudo 

I was going to report an issue in this package to Miquel de Caceres (a former colleague at university) but he kindly pointed to you as the main leader of this package :-) 

I was missing HR values in the daily records obtained from AEMET through meteospain. I see that they are present in instant and hourly values, and monthly, but not daily. 
https://github.com/emf-creaf/meteospain/blob/63972c1c22a4ef59ecb1f64a60e48dad59e0b855/R/aemet_helpers.R#L479

Was that in purpose for some reason or just some sort of bug?

**Comment by MalditoBarbudo** [comment]
This was on purpose as the RH values were not present in the previous version of the API. It seems that they have updated the API, including new limits (#25) but also to include RH in daily.

Working on it.

**Comment by MalditoBarbudo** [comment]
- [ ] `.aemet_daily_carpentry`: update missing vars, check units
- [ ] update tests to check new vars

**Comment by MalditoBarbudo** [comment]
Fixed in devel

**Comment by MalditoBarbudo** [comment]
@xavidp If you install the devel version with `devtools` or `remotes` this should be fixed and HR values are returned in daily scale

**Comment by xavidp** [comment]
Fix confirmed also! (the variables I reported that were missing are nowadays included). Congrats and thanks heaps!
